project_name: ficsit

before:
  hooks:
    - go generate -x -tags tools ./...
    - go mod tidy

builds:
  - id: with-upx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - 386
    goarm:
      - 7
    hooks:
      post: 'upx {{ .Path }}'
  - id: without-upx
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 7

universal_binaries:
  - replace: true
    ids:
      - without-upx

archives:
  - format: binary
    allow_different_binary_count: true
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

nfpms:
  - vendor: Satisfactory Modding
    homepage: https://ficsit.app/
    maintainer: Satisfactory Modding Team <support@ficsit.app>
    description: CLI tool for Ficsit (Satisfactory Modding)
    license: GNU General Public License v3.0
    file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}"
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

aurs:
  - name: ficsit-cli-bin
    description: A CLI for managing mods for the game Satisfactory
    homepage: https://github.com/satisfactorymodding/ficsit-cli
    maintainers:
      - 'Vilsol <me at vil dot so>'
    license: GPL3
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/ficsit-cli-bin.git'
    package: |
      install -Dm755 "./${pkgname}_${pkgver}_${CARCH}.binary" "${pkgdir}/usr/bin/ficsit"