version: '2'

services:
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    volumes:
      - ./SatisfactoryDedicatedServer:/home/user/server
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=user